//  Amiibo
export const FETCH_TYPES = 'FETCH_TYPES';
export const FETCH_AMIIBOS = 'FETCH_AMIIBOS';
export const FETCH_AMIIBOS_TYPES = 'FETCH_AMIIBOS_TYPES';
export const FETCH_INITIAL_STATE = 'FETCH_INITIAL_STATE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
